package com.restfull.demo.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

public class CreateTable {

    public void connectDataBase(String email, String password){
        Connection c = null;
        Statement stmt = null;
        String CreateSql = null;
        String useBD;
        try{
            Class.forName("org.postgresql.Driver");
            c = DriverManager.getConnection("jdbc:postgresql://ec2-3-226-231-4.compute-1.amazonaws.com:5432/d8r63a245jnejl?password=e516096139537dc1b49ad3cef4080430985dd02ba7fd528627909bfb5e94a795&sslmode=require&user=vnbnnvncshvnad");
            System.out.println("Database Connected ..");
            stmt = c.createStatement();
//            CreateSql = "Create Table Users(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email varchar UNIQUE, password text) ";
            stmt.executeUpdate(setData(email,password));
            stmt.close();
            c.close();
        }
        catch (Exception e)
        {
            System.err.println( e.getClass().getName()+": "+ e.getMessage() );
            System.exit(0);
        }
        System.out.println("Table Created successfully");
    }

    public String setData (String email, String password){
        return String.format("INSERT INTO Users(email, password ) VALUES ('%s', '%s');",email,password);
    }
}
